### ISSUE TITLE
identity file is not recognized

### ISSUE THREAD

**Issue by tristan-k** [neverpanic/simpleid-yubikey#1]
I followed the instruction properly but I'm unable to login because: 

`01.10.2015 01:57:03 83q3r9e45m2i9sq0mt0t0d0q41 [WARN] auth_method method for  is YUBIKEY, but the yubikey section is missing from the identity file.`

Even though the files are there and the yubikey section exists.

**Comment by neverpanic** [comment]
Which version of simpleid are you running?

**Comment by tristan-k** [comment]
I'm running version 0.9.1.

**Comment by neverpanic** [comment]
Actually, the code that prints this message is

``` php
    $test_user = user_load($uid);

    // check for required settings in the identity file
    if (!isset($test_user['yubikey']) || !is_array($test_user['yubikey'])) {
        log_warn('auth_method method for ' . $test_user['uid'] . ' is YUBIKEY, but the yubikey section is missing ' .
            'from the identity file.');
        return false;
    }
```

So it seems that `user_load($uid)` returned something that is either not set or not an array. `$uid` cannot have been `NULL`, otherwise you would have seen a different error message. However, `$test_user['uid']` was an empty string or something that expands to an empty string.

How does your identity file look like (anonymized, of course)? What are the contents of your user store file? Do you have stuff in cache?

**Comment by neverpanic** [comment]
Reading further into the code, `user_load()` must have been called with an empty string, because it copies its argument into `$user['uid']`:

``` php
function user_load($uid) {
    if (store_user_exists($uid)) {
        $user = store_user_load($uid);
        $user["uid"] = $uid;

        // ...

        return $user;
    } else {
        return NULL;
    }
}
```

 and `store_user_exists($uid)` must have succeeded. `store_user_exists()` accepts empty UIDs (that sounds like a bug in simpleid) and will return true if your identity file's name is `.identity`.

Or maybe it's just a caching issue? I've added some code that should help in debugging and is generally a good idea as sanity check.

**Comment by tristan-k** [comment]
Thanks for your efforts. I stepped up the debug level to 5. Now there is different output. It seems the auth failed but it's strange because my [validation server](https://github.com/digintLab/yubikey-server) is just running fine. 

`$ ls store/
tristank.usrstore  site-token.setting`

`$ ls cache/
user  user-nonce  yubikey`

`$ ls cache/yubikey/
c3211d833c1af296a3eff8fff7cea191.cache`

`tristank.identity` 

```
identity="https://auth.tristank.de/"
pass="unused"
administrator=1

auth_method="YUBIKEY"

[yubikey]
client_id="1"
client_key="AaAaAaAaAaAaAaAaAaAaAaAaAaA="
use_https=1
key_id="hdvbhdvbillt"
URLs[]="tristank.de:61222/wsapi/2.0/verify"
```

`$ tail -f /home/tristank/html/simpleid/debug.log`  

```
01.10.2015 21:17:26  [DEBUG] user_init
01.10.2015 21:17:26 brh1d2v3kk3l77krbo9c60eo14 [DEBUG] extension_invoke: user_cookieauth_user_auto_login
01.10.2015 21:17:26 brh1d2v3kk3l77krbo9c60eo14 [INFO] Session opened for "" from 81b21459c3cfe33a1546da4d216efb67 [78.48.243.255, f048243255.adsl.alicedsl.de]
01.10.2015 21:17:26 brh1d2v3kk3l77krbo9c60eo14 [DEBUG] extension_invoke_all: ui_routes
01.10.2015 21:17:26 brh1d2v3kk3l77krbo9c60eo14 [DEBUG] simpleid_index
01.10.2015 21:17:26 brh1d2v3kk3l77krbo9c60eo14 [DEBUG] extension_invoke_all: ui_user_login_form
01.10.2015 21:17:26 brh1d2v3kk3l77krbo9c60eo14 [DEBUG] extension_invoke_all: yubikey_user_login_form
01.10.2015 21:17:36  [DEBUG] user_init
01.10.2015 21:17:36 brh1d2v3kk3l77krbo9c60eo14 [INFO] Session opened for "login" from 81b21459c3cfe33a1546da4d216efb67 [78.48.243.255, f048243255.adsl.alicedsl.de]
01.10.2015 21:17:36 brh1d2v3kk3l77krbo9c60eo14 [DEBUG] extension_invoke_all: ui_routes
01.10.2015 21:17:36 brh1d2v3kk3l77krbo9c60eo14 [DEBUG] extension_invoke: yubikey_user_verify_credentials
01.10.2015 21:17:36 brh1d2v3kk3l77krbo9c60eo14 [DEBUG] authentication against yubikey server for user tristank failed.
01.10.2015 21:17:36 brh1d2v3kk3l77krbo9c60eo14 [DEBUG] extension_invoke: user_passauth_user_verify_credentials
01.10.2015 21:17:36 brh1d2v3kk3l77krbo9c60eo14 [DEBUG] extension_invoke_all: ui_user_login_form
01.10.2015 21:17:36 brh1d2v3kk3l77krbo9c60eo14 [DEBUG] extension_invoke_all: yubikey_user_login_form
```

`

**Comment by neverpanic** [comment]
Interesting, this debug output indicates the code continued up to the point where the OTP is being validated, passing the point where it bailed out earlier. Maybe it was just a caching issue after all.

Looking at the code, the debug message should really tell you _why_ the authentication failed. I'll push that in a second.

**Comment by tristan-k** [comment]
Here is the output again:

```
01.10.2015 22:12:03 brh1d2v3kk3l77krbo9c60eo14 [DEBUG] extension_invoke_all: ui_routes
01.10.2015 22:12:03 brh1d2v3kk3l77krbo9c60eo14 [DEBUG] extension_invoke: yubikey_user_verify_credentials
01.10.2015 22:12:03 brh1d2v3kk3l77krbo9c60eo14 [DEBUG] authentication against yubikey server for user tristank failed: NO_VALID_ANSWER
01.10.2015 22:12:03 brh1d2v3kk3l77krbo9c60eo14 [DEBUG] extension_invoke: user_passauth_user_verify_credentials
01.10.2015 22:12:03 brh1d2v3kk3l77krbo9c60eo14 [DEBUG] extension_invoke_all: ui_user_login_form
01.10.2015 22:12:03 brh1d2v3kk3l77krbo9c60eo14 [DEBUG] extension_invoke_all: yubikey_user_login_form
```

I don't get it! I followed the instruction for [yubikey-server](https://github.com/digintLab/yubikey-server#how-to-query-the-server) on how to query the server and the response is the expected. 

http://tristank.de:61222/wsapi/2.0/verify?otp=vvbknblkghifjtugehbdgfhtbrcghrufghihfjkbifdg&id=3&nonce=test42

```
nonce=test42
otp=vvbknblkghifjtugehbdgfhtbrcghrufghihfjkbifdg
status=OK
t=2015-10-01T22:14:29+02:00
h=EX1dBHimYyaCLZj0g7d0G6MYgm4=`
```

So maybe it isnt a simpleid-yubikey issue then ...

**Comment by neverpanic** [comment]
Compare:

```
$ curl -sL 'http://tristank.de:61222/wsapi/2.0/verify?otp=vvbknblkghifjtugehbdgfhtbrcghrufghihfjkbifdg&id=3&nonce=test42' | xxd -i | grep 0x0d
```

with

```
$ curl -sL 'https://yubiserve.neverpanic.de:8001/wsapi/2.0/verify?otp=fdsfsdfs' | xxd -i | grep 0x0d
```

For some reason, the Yubico.php validation class requires `\r\n` line endings.

**Comment by tristan-k** [comment]
Thanks again. So it's not related to simpleid-yubikey. Which validation server are you using? Yubico-yubiserve (https://github.com/rbarrois/yubico-yubiserve/) or the official one?

**Comment by neverpanic** [comment]
yubico-yubiserve, but with a couple of patches on top IIRC to make the SSL cert work. I'm not really satisfied with it because the code shows its age, though. However, out of the servers I actually looked at, it still seemed the most secure one (especially because it's small enough to do a complete audit).

I'm quite interested in your project, it seems like that could be a server to replace my current setup. I like that you went with a safe language… which reminds me, I should really do full disclosure on that other server in Debian with open security issues by now.

I guess I can close this ticket then, or do you want to turn it into simepleid-yubico should accept `\n` as line endings?

**Comment by tristan-k** [comment]
I read about the [security issues](http://blog.quarkslab.com/why-2fa-would-not-have-saved-ht.html). In fact that was the reason to choose yubikey-server in the first place. I would love to see simpleid-yubikey to be compatible with yubikey-server. They are a great match!

**Comment by neverpanic** [comment]
I guess this should really be fixed in Yubico/php-yubico then. See also Yubico/php-yubico#14, which could be the same issue. Looking at Yubico/php-yubico#5 also looks like this code isn't really secure :/

Anyway, my copy of this is severely outdated, so I can at least update it, and then take a shot at a fix.

Btw, that was actually not the security issue I was talking about... it seems implementing a Yubico validation server properly is hard enough that nobody gets it right (or easy enough that everybody attempts it...).

**Comment by neverpanic** [comment]
Can you try the accept-nl-only branch and see if that helps? I cannot easily test since I have no server that sends `\n`.

**Comment by tristan-k** [comment]
No, it does not. Still no valid answer. 

```
02.10.2015 01:07:03 brh1d2v3kk3l77krbo9c60eo14 [DEBUG] extension_invoke_all: ui_routes
02.10.2015 01:07:03 brh1d2v3kk3l77krbo9c60eo14 [DEBUG] extension_invoke: yubikey_user_verify_credentials
02.10.2015 01:07:03 brh1d2v3kk3l77krbo9c60eo14 [DEBUG] authentication against yubikey server for user tristank failed: NO_VALID_ANSWER
02.10.2015 01:07:03 brh1d2v3kk3l77krbo9c60eo14 [DEBUG] extension_invoke: user_passauth_user_verify_credentials
02.10.2015 01:07:03 brh1d2v3kk3l77krbo9c60eo14 [DEBUG] extension_invoke_all: ui_user_login_form
02.10.2015 01:07:03 brh1d2v3kk3l77krbo9c60eo14 [DEBUG] extension_invoke_all: yubikey_user_login_form
```

**Comment by tristan-k** [comment]
Do you have a Yubikey with a free slot available? I could add your publicKey and  AESSecret to my database. After testing is finished you could reprogram it.

**Comment by neverpanic** [comment]
Unfortunately I'm using both slots of my only Yubikey actively. I guess I'll just dive further into the code and look for other possible problems and end up installing my own copy of the validation server -- I was looking for a good alternative for a while anyway.

**Comment by neverpanic** [comment]
Found the problem: In yubikey-server, the application key used to sign the responses is stored as base64, as it is in both yubico-yubiserve and simpleid-yubikey. However, both yubico-yubiserve and simpleid-yubikey decode the base64 into binary data before passing it to the HMAC function, whereas yubikey-server uses the ASCII base64 representation as raw bytes. Obviously that's a different key and thus leads to a different signature, which makes the validation fail.

I have a patch that changes this behavior in yubikey-server, but it's obviously not backwards-compatible: Any signature verifications in clients of yubikey-server that did previously work (are there any?) would immediately fail with this change.

I'll fork your repo and push the changes in a second.

**Comment by neverpanic** [comment]
Please note that this is the first time I write go code, so please be gentle and pull with care and review.

**Comment by tristan-k** [comment]
Thanks. It's still not working for me. 

     $ tail -f debug.log 
     11.10.2015 19:47:42  [DEBUG] user_init
     11.10.2015 19:47:42 pacipj5lsa4c6kcp2ahen201p5 [INFO] Session opened for "login" from ae4c7f07c53d89744a7960278f299261 [77.181.180.176, x4db5b4b0.dyn.telefonica.de]
     11.10.2015 19:47:42 pacipj5lsa4c6kcp2ahen201p5 [DEBUG] extension_invoke_all: ui_routes
     11.10.2015 19:47:42 pacipj5lsa4c6kcp2ahen201p5 [WARN] Login attempt: Nonce 2015-10-11T17:34:25Z6a89b7d7 not issued or is being reused.
     11.10.2015 19:47:42 pacipj5lsa4c6kcp2ahen201p5 [DEBUG] extension_invoke_all: ui_user_login_form
     11.10.2015 19:47:42 pacipj5lsa4c6kcp2ahen201p5 [DEBUG] extension_invoke_all: yubikey_user_login_form
     11.10.2015 19:47:56  [DEBUG] user_init
     11.10.2015 19:47:56 pacipj5lsa4c6kcp2ahen201p5 [INFO] Session opened for "login" from ae4c7f07c53d89744a7960278f299261 [77.181.180.176, x4db5b4b0.dyn.telefonica.de]
     11.10.2015 19:47:56 pacipj5lsa4c6kcp2ahen201p5 [DEBUG] extension_invoke_all: ui_routes
     11.10.2015 19:47:56 pacipj5lsa4c6kcp2ahen201p5 [DEBUG] extension_invoke: yubikey_user_verify_credentials
     11.10.2015 19:47:56 pacipj5lsa4c6kcp2ahen201p5 [DEBUG] authentication against yubikey server for user tristank failed: NO_VALID_ANSWER
     11.10.2015 19:47:56 pacipj5lsa4c6kcp2ahen201p5 [DEBUG] extension_invoke: user_passauth_user_verify_credentials
     11.10.2015 19:47:56 pacipj5lsa4c6kcp2ahen201p5 [DEBUG] extension_invoke_all: ui_user_login_form
     11.10.2015 19:47:56 pacipj5lsa4c6kcp2ahen201p5 [DEBUG] extension_invoke_all: yubikey_user_login_form

There is different output if I query the server with a http call:

     $ http://tristank.de:65150/wsapi/2.0/verify?otp=vvbknblkghifkhtrdjkjgduiulndcjdbhediungflnug&id=1&nonce=test42
     nonce=test42
     otp=vvbknblkghifkhtrdjkjgduiulndcjdbhediungflnug
     status=illegal base64 data at input byte 0
     t=2015-10-11T19:50:07+02:00
     h=aBxss4BobDpAiYL/yIU8GsQu/MI=

**Comment by tristan-k** [comment]
Thanks. It's still not working for me. 

```
 $ tail -f debug.log 
 11.10.2015 19:47:42  [DEBUG] user_init
 11.10.2015 19:47:42 pacipj5lsa4c6kcp2ahen201p5 [DEBUG] extension_invoke_all: ui_routes
 11.10.2015 19:47:42 pacipj5lsa4c6kcp2ahen201p5 [WARN] Login attempt: Nonce 2015-10-11T17:34:25Z6a89b7d7 not issued or is being reused.
 11.10.2015 19:47:42 pacipj5lsa4c6kcp2ahen201p5 [DEBUG] extension_invoke_all: ui_user_login_form
 11.10.2015 19:47:42 pacipj5lsa4c6kcp2ahen201p5 [DEBUG] extension_invoke_all: yubikey_user_login_form
 11.10.2015 19:47:56  [DEBUG] user_init
 11.10.2015 19:47:56 pacipj5lsa4c6kcp2ahen201p5 [DEBUG] extension_invoke_all: ui_routes
 11.10.2015 19:47:56 pacipj5lsa4c6kcp2ahen201p5 [DEBUG] extension_invoke: yubikey_user_verify_credentials
 11.10.2015 19:47:56 pacipj5lsa4c6kcp2ahen201p5 [DEBUG] authentication against yubikey server for user tristank failed: NO_VALID_ANSWER
 11.10.2015 19:47:56 pacipj5lsa4c6kcp2ahen201p5 [DEBUG] extension_invoke: user_passauth_user_verify_credentials
 11.10.2015 19:47:56 pacipj5lsa4c6kcp2ahen201p5 [DEBUG] extension_invoke_all: ui_user_login_form
 11.10.2015 19:47:56 pacipj5lsa4c6kcp2ahen201p5 [DEBUG] extension_invoke_all: yubikey_user_login_form
```

There is different output if I query the server with a http call:

```
 $ http://tristank.de:65150/wsapi/2.0/verify?otp=vvbknblkghifkhtrdjkjgduiulndcjdbhediungflnug&id=1&nonce=test42
 nonce=test42
 otp=vvbknblkghifkhtrdjkjgduiulndcjdbhediungflnug
 status=illegal base64 data at input byte 0
 t=2015-10-11T19:50:07+02:00
 h=aBxss4BobDpAiYL/yIU8GsQu/MI=
```

**Comment by neverpanic** [comment]
OK, so I guess my change is bad and I should really give the error handling more thought.

I'm not exactly sure which part of the base64 decoding fails at this point. It could be where it reads the key from the database; I only tested this with freshly created keys.

**Comment by neverpanic** [comment]
Please try again with what I just pushed.

**Comment by neverpanic** [comment]
OK, so the patch has been merged upstream, please try again with the accept-nl-only branch when you have time. That should fix the issue.
